# Generated by Django 3.2.9 on 2021-11-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('contraseña', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=100)),
                ('edad', models.CharField(max_length=3)),
                ('apodo', models.CharField(max_length=20)),
            ],
        ),
    ]
